<?php
/**
 * Admin sidebar navigation — slug must match keys in page.php $ADMIN_PAGES (except dashboard).
 */
return [
    ['link', 'dashboard', 'Dashboard', 'fa-gauge-high', 'index.php'],
    ['section', 'Members Management'],
    ['link', 'members-all', 'All Members', 'fa-users', null],
    ['link', 'members-approval', 'Member Approvals', 'fa-user-check', null],
    ['link', 'members-approved-paid', 'Approved → Paid Members', 'fa-circle-check', null],
    ['link', 'members-renew', 'Renew Membership Plan', 'fa-rotate', null],
    ['link', 'members-featured', 'Manage Featured Members', 'fa-star', null],
    ['link', 'members-deactivation', 'Profile Deactivation Requests', 'fa-user-slash', null],
    ['section', 'Membership Plans'],
    ['link', 'plans-add', 'Add Membership Plan', 'fa-plus-circle', null],
    ['link', 'plans-all', 'All Membership Plans', 'fa-list-ul', null],
    ['section', 'Profile Master Data'],
    ['link', 'master-religion', 'Religion', 'fa-place-of-worship', null],
    ['link', 'master-caste', 'Caste', 'fa-people-group', null],
    ['link', 'master-subcaste', 'Sub Caste', 'fa-users-line', null],
    ['link', 'master-gotra', 'Gotra', 'fa-book-open', null],
    ['link', 'master-country', 'Country', 'fa-globe', null],
    ['link', 'master-state', 'State', 'fa-map', null],
    ['link', 'master-city', 'City', 'fa-city', null],
    ['link', 'master-occupation', 'Occupation', 'fa-briefcase', null],
    ['link', 'master-education', 'Education', 'fa-graduation-cap', null],
    ['link', 'master-mother-tongue', 'Mother Tongue', 'fa-language', null],
    ['link', 'master-star', 'Star', 'fa-star-of-david', null],
    ['link', 'master-rasi', 'Rasi (Moonsign)', 'fa-moon', null],
    ['link', 'master-income', 'Annual Income', 'fa-indian-rupee-sign', null],
    ['link', 'master-dosh', 'Dosh', 'fa-yin-yang', null],
    ['section', 'Match Making'],
    ['link', 'match-suggestions', 'Match Suggestions', 'fa-heart', null],
    ['link', 'match-compatibility', 'Compatibility Settings', 'fa-sliders', null],
    ['section', 'Payments'],
    ['link', 'payments-history', 'Payment History', 'fa-receipt', null],
    ['link', 'payments-manual', 'Manual Payments', 'fa-hand-holding-dollar', null],
    ['link', 'payments-methods', 'Payment Methods', 'fa-credit-card', null],
    ['section', 'Approvals'],
    ['link', 'approval-horoscope', 'Horoscope Approval', 'fa-file-pdf', null],
    ['link', 'approval-document', 'Document Approval', 'fa-file-lines', null],
    ['link', 'approval-photo', 'Profile Picture Approval', 'fa-camera', null],
    ['link', 'approval-gallery', 'Gallery Photo Approval (2–8)', 'fa-images', null],
    ['link', 'approval-about', 'About Me Approval', 'fa-user-pen', null],
    ['link', 'approval-partner', 'Partner Expectation Approval', 'fa-hand-holding-heart', null],
];
